name: language_learning
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/numbers/
    - assets/images/family_members/
    - assets/images/colors/
    - assets/sounds/numbers/
    - assets/sounds/family_members/
    - assets/sounds/colors/
    - assets/sounds/phrases/

